id: P007087
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18570
  title: ཀྲུའུ་ཏེའི་གསུང་རྩོམ་གཅེས་བསྡུས།
  author: ''
  volumes:
    d4430d9e30ce4c4ba59d61f2741bb954:
      image_group_id: I1KG18657
      title: ''
      volume_number: 1
      total_pages: 834
ebook_metadata:
  title: ཀྲུའུ་ཏེའི་གསུང་རྩོམ་གཅེས་བསྡུས།
  author: ''
  sku: P007087
  cover: cover.jpg
  layers:
  - pagination
