id: P007087
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18570
  title: ཀྲུའུ་ཏེའི་གསུང་རྩོམ་གཅེས་བསྡུས།
  author: ''
  volumes:
    69454d5ff8bf402e9a3ceec7135eb43c:
      image_group_id: I1KG18657
      title: Volume 1 of kru'u te'i gsung rtsom gces bsdus/
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
ebook_metadata:
  title: ཀྲུའུ་ཏེའི་གསུང་རྩོམ་གཅེས་བསྡུས།
  author: ''
  sku: P007087
  cover: cover.jpg
  layers:
  - pagination
