id: P007087
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:40:41.806229
source_metadata:
  id: bdr:W1KG18570
  title: ཀྲུའུ་ཏེའི་གསུང་རྩོམ་གཅེས་བསྡུས།
  author: ''
  volumes:
    69454d5ff8bf402e9a3ceec7135eb43c:
      image_group_id: I1KG18657
      title: Volume 1 of kru'u te'i gsung rtsom gces bsdus/
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
